export const SUCCESS_MESSAGES = {
	CREATED: "Successfully Created.",
	ADDED: "Successfully Added.",
	UPDATED: "Successfully Updated.",
	DELETED: "Successfully Deleted.",
	CANCELLED: "Successfully Cancelled.",
	USER_REGISTERED: "User registered successfully",
	VENDOR_REGISTERED: "Login and complete your profile",
	BUILDING_REGISTERED: "Building registered successfully",
	BUILDING_RE_REGISTERED: "Building re-applied successfully. Please wait for admin approval.",
	OTP_SENT: "OTP sent successfully",
	OTP_VERIFIED: "OTP verified successfully",
	Token_VERIFIED: "Token verified successfully",
	LOGIN_SUCCESS: "Login Success.",
	PASSWORD_RESET_LINK_SENT: "Password reset link sent to your email",
	PASSWORD_RESET_SUCCESS: "Password reset successfully",
	LOGOUT_SUCCESS: "Logout successful",
	TOKEN_REFRESHED: "Token refreshed successfully",
	PAYMENT_INTENT_CREATED: "Payment intent created successfully.",
	PAYMENT_CONFIRMED: "Payment confirmed successfully.",
	BOOKINGS_FETCHED: "Bookings fetched successfully.",
	USER_DATA_FETCHED: "User data fetched successfully.",
	FETCHED: "Fetched successfully",
    CHAT_CLEARED: "Chat cleared successfully.",
    ID_PROOF_UPLOADED: "ID proof uploaded successfully",
	WALLET_DETAILS_RETRIEVED: "Wallet details retrieved successfully",
	BOOKING_CONFIRMED: "Booking confirmed",
} as const;

export const ERROR_MESSAGES = {
	EMAIL_EXIST: 'This email is already registered.',
	OFFER_EXIST: "An overlapping offer already exists for the selected space and time range.",
	MISSING_CREDENTIALS: "Credentials Missing.",
	INVALID_ROLE: "Invalid role",
	INVALID_TOKEN: "Invalid Token",
	INVALID_LOCATION_DATA: "Invalid location data format",
	INVALID_CREDENTIALS: "Invalid email or password",
	VENDOR_PENDING: "Your vendor account has not yet been approved by the admin.",
	VENDOR_REJECTED: "Your vendor account has been rejected by the admin. Check your email for more details.",
	USER_BLOCKED: "Your account has been blocked by the admin.",
	MISSING_DATA: "Missing data",
	INVALID_EMAIL_FORMAT: "Invalid email format",
	INVALID_PASSWORD_FORMAT: "Invalid password format",
	USER_NOT_FOUND: "User not found",
	BOOKING_NOT_FOUND: "Booking not found",
	SPACE_NOT_FOUND: "Space not found",
	BUILDING_NOT_FOUND: "Building not found",
	CHAT_SESSION_NOT_FOUND: "Chat session not found",
	ENTITY_NOT_FOUND: "Entity not found",
	SPACE_NOT_AVAILABLE: 'Space is no longer available',
	BOOKING_CONFLICT: "This space is temporarily unavailable due to high demand. Please refresh and try booking again.",
	UNAUTHORIZED: "Unauthorized",
	MISSING_TOKEN_DATA: "User ID, email, or role is missing",
	REFRESH_TOKEN_MISSING: "No refresh token found",
	AMENITY_NAME_REQUIRED: "Amenity name is required and must be a string.",
	AMENITY_EXIST: "Amenity with this name already exists.",
	AMENITY_DONT_EXIST: "Amenity does not exist.",
	SPACE_ID_REQUIRED: "Space Id is required.",
	BUILDING_ID_REQUIRED: "Building Id is required.",
	ID_PROOF_REQUIRED: "Space Id is required.",
	BOOKING_ID_REQUIRED: "Booking Id is required.",
	BOOKING_ID_REASON_REQUIRED: "Booking Id and Reason is required.",
	FAILED:"Failed to complete the action. Please try again.",
	FAILED_UPDATE_SUMMARIZED_SPACE_BUILDING:"Failed to update summarized Spaces in building",
	VALIDATION_FAILED: "Validation failed",
	FAILE_TO_STORE_TOKEN_IN_REDIS: "Failed to store reset token",
    INVALID_EMAIL:"Invalid email. Please try again with another email",
    INVALID_PASSWORD:"Password is invalid. Please try again.",
    INVALID_REFRESH_TOKEN:'Invalid refresh token',
    INCORRECT_OTP:"The OTP you entered is incorrect or has expired. Please try again or request a new OTP.",
	ID_ROLE_REQUIRED: "User ID and role is required.",
	BOOKING_ALREADY_CANCELLED: "Booking is already cancelled",
	NOT_ALLOWED: "You are not allowed to cancel this booking.",
	PAYMENT_INTENT_STATUS_INCORRECT: 'Payment intent is not in the correct state for confirmation',
	ADMIN_ID_NOT_FOUND: "Admin ID not configured, Please contact support.",
	INVALID_BOOKING_ID: 'Invalid booking ID or booking cannot be retried',
	BUILDING_EXIST: "A building with this name and location already exists.",
	INVALID_ENTITY_TYPE: "Invalid entity type",
	INVALID_STATUS: "Invalid Status",
	INSUFFICIENT_WALLET_BALANCE: "Insufficient wallet balance.",
	USER_UNAUTHORIZED: "User is unauthorized",
	TOKEN_BLACKLISTED: "Token is blacklisted",
	UNKNOWN_ERROR: "An unknown error occurred",
	BLOCKED_USER: "Access denied: Your account has been blocked",
	INTERNAL_SERVER_ERROR: "Internal server error",
	SESSION_EXPIRED: "Your session has expired. Please log in again.",
	RESET_TOKEN_SECRET_ERROR: "RESET_TOKEN_SECRET is not defined in environment variables",
	STRIPE_SECRET_KEY_ERROR: 'STRIPE_SECRET_KEY is not configured',
	FIREBASE_ERROR: "Firebase service account file not found",
	CHAT_SOCKET_ERROR: "ChatSocketHandler not initialized.",
	NOTIFICATION_HANDLER_ERROR: "NotificationSocketHandler not initialized.",
	INVALID_AUTHENTICATION_DATA: "Invalid authentication data",
	AUTHENTICATION_FAILED: "Authentication failed",
} as const;

export const INFO_MESSAGES = {
	REDIRECT_VENDOR_PENDING: "Your vendor account is pending admin approval.",
	REDIRECT_VENDOR_REJECTED: "Your vendor account has been rejected. Please check your email for more details.",
	APPLICATION_RETRIED: "Your application has been retried with the updated details. Please wait while the admin reviews and approves it.",
} as const;

